LOAD DATA LOCAL INFILE 'csv/item.csv' INTO TABLE Item 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'csv/user.csv' INTO TABLE User 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'csv/category.csv' INTO TABLE Category 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'csv/bid.csv' INTO TABLE Bid 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'csv/itemseller.csv' INTO TABLE ItemSeller 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'csv/itemcategory.csv' INTO TABLE ItemCategory 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';